baseURL = "/"
relativeurls = true
languageCode = "ja"
title = "command not found:"
theme = "hugo-minimal"

[params]
  googleAnalytics = "G-T35T2MCR4K"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "Profile"
  url = "https://hub.zinrai.info"
  weight = 2
